# Generated by Django 4.1.3 on 2022-11-07 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Código unico', max_length=32, unique=True)),
                ('departure', models.TimeField(help_text='Expected flight departure time')),
                ('duration', models.DurationField(help_text='Expected duration')),
            ],
            options={
                'ordering': ['departure'],
            },
        ),
        migrations.CreateModel(
            name='FlightInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Code for instance, it will concat to flight', max_length=32)),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Delayed', 'Delayed'), ('Departed', 'Departed'), ('In Air', 'In Air'), ('Expected', 'Expected'), ('Diverted', 'Diverted'), ('Recovery', 'Recovery'), ('Landed', 'Landed'), ('Arrived', 'Arrived'), ('Cancelled', 'Cancelled'), ('No Takeoff Info', 'No Takeoff Info - Call Airline'), ('Past Flight', 'Past Flight')], default='Scheduled', max_length=32)),
                ('departure', models.TimeField(help_text='Real flight departure time')),
                ('duration', models.DurationField(help_text='Real duration')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='flight.flight')),
            ],
            options={
                'ordering': ['departure'],
            },
        ),
    ]
