# Generated by Django 4.1.3 on 2022-11-25 17:53

from django.conf import settings
from django.db import migrations

def create_users(apps, editor):
    User = apps.get_model(settings.AUTH_USER_MODEL)
    User.objects.create_superuser('admin', 'admin@mail.com', '1234')
    User.objects.create('manager', 'manager@mail.com', '1234')
    User.objects.create('operation', 'manager@mail.com', '1234')
    User.objects.create('pilot', 'pilot@mail.com', '1234')

class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_users, migrations.RunPython.noop),
    ]
