# Generated by Django 4.1.3 on 2022-11-25 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightinstance',
            name='status',
            field=models.CharField(choices=[('Scheduled', 'Scheduled'), ('Onboarding', 'Onboarding'), ('Taxing', 'Taxing'), ('Departed', 'Departed'), ('Arrived', 'Arrived'), ('Cancelled', 'Cancelled')], max_length=32),
        ),
    ]
