# Generated by Django 4.1.3 on 2022-12-08 18:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flight", "0002_users"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flight",
            name="code",
            field=models.CharField(
                help_text="Unique code, 3 letters followed by numbers",
                max_length=32,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[A-Z]{3}[0-9]+$", "Code must be in the format ABC1234"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="flight",
            name="direction",
            field=models.CharField(
                choices=[("Arrival", "Arrival"), ("Departure", "Departure")],
                default="Departure",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="flight",
            name="time",
            field=models.TimeField(
                help_text="Expected time for departure or arrival, in HH:MM format"
            ),
        ),
        migrations.AlterField(
            model_name="flightinstance",
            name="code",
            field=models.CharField(
                help_text="Code for instance, it will concat to flight's code, numbers only",
                max_length=32,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[0-9]+$", "Code must be in the format 1234"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="flightinstance",
            name="status",
            field=models.CharField(
                choices=[
                    ("Boarding", "Boarding"),
                    ("Scheduled", "Scheduled"),
                    ("Taxing", "Taxing"),
                    ("Ready", "Ready"),
                    ("Authorized", "Authorized"),
                    ("In flight", "In flight"),
                    ("Landed", "Landed"),
                    ("Canceled", "Canceled"),
                ],
                default="Boarding",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="flightinstance",
            name="time",
            field=models.DateTimeField(
                help_text="Real time for departure or arrival, in YYYY-MM-DD HH:MM format"
            ),
        ),
    ]
